remote_theme: pages themes/cayman@v0.2.0:
# UFG
---
layout: default
title: "Кваліфікаційна робота"
---

# Кваліфікаційна робота

## Про проект
Кваліфікаційна робота на підтвердження ступеня фахового молодшого бакалавра ([ВСП «ППФК НТУ «ХПІ»](http://polytechnic.poltava.ua)).  
Керівник роботи – **Зелінська Анастасія Олександрівна**.

## Завдання до дипломної роботи
Розроблений програмний продукт є однокористувацькою грою в жанрі "action/RPG", створеною для персональних комп’ютерів. У грі гравець зможе:
- змінювати зброю (наприклад, меч на лук і навпаки);
- налаштовувати зовнішній вигляд персонажа;
- взаємодіяти з ворогами;
- стежити за шкалою здоров'я головного героя.

Мова розробки - **GDScript**, середовище розробки - **Godot**.

## Використані технології
- Godot Engine
- GDScript

---
© 2024
